/**
 * Principles:
 * - Decentralized system
 * - There are many Banks that maintain ledgers for Vouchers
 * - Banks transact using a 3 phase protocol (approve, hold, settle)
 * - The parties only see entities and records that are relevant to them rather than the whole ledger
 * - Transactions might stall or get abandoned - the lead party bears the risk and reposibility to recover
 * - Use JSON RPC 2.0
 * 
 * Remaining sections:
 * - Address routing (pubkey -> url mapping)
 * - Bank to Bank interface - how banks let other banks know
 * - Naming (pubkey -> domainname)
 * - Hosting - adhoc as it doesn't require interoperability
 * - Content Feeds and Comments
 

 * AI Arena:
 * - bots generate vouchers and post on X using a hashtag #voucher
 * - find other bots on X and subscribe to their vouchers
 * - create orders to exchange vouchers, determine a rate
 * 
 * AI prompts:
 * - design a convenience library with functions. give me only the function signatures and descriptions of what they do.
 * I'll start:
 * 
 * 
 * 
 */

/**
 * These named types help define the format of the string properties.
 */
export type Base58PubKey = string; // example: "CqPmMncin5kkUJpLgUmy78mfp1GQiaxvDpjwihgnmiza"
export type Base58SHA256 = string; // example: "48FsxVa3TEK2i698HiBZnsGNmaakr9kmi4J7HVkgL6Ke"
export type Base58Signature = string; // example: "3yNbAzZ7GZJwSFkrhNxUia78o2SnhFL8ttxhWUNFva8oTVMfw7hk1NL3TsAsWQz6CPGx6WbS1SPFbZLgBZYvcbPM"
export type ULID = string; // example: "01J84XCEPZ8B7K3NJ60ZBQX4K3"
export type DateString = string; // YYYY-MM-DD ISO 8601, example: "2024-05-02"
export type Currency = string; // example: "USD"
export type Seconds = number; // example: 600

/**
 * Most of the data entities exchanged between the parties are signed documents. The documents are immutable and eternal - 
 * they never change and never expire.
 * 
 * Each document has the following properties:
 * - type: Determines the document's purpose and schema
 * - pubkey: public key of the document's owner. Encoded using base58. 
 * Here and below the Pubkey Owner is the party having the private key corresponding to the Pubkey
 * - ulid: Universally Unique Lexicographically Sortable Identifier assigned at creation.
 * 
 * Specific document instances contain additional properties depending on the type.
 * The document is not valid without an owner's signature. The signature is provided in a separate entity of type Signature 
 * (see below) that links to the document using its hash.
 * Document ulid property contains an encoded timestamp, eliminating the need for a separate creation date property.
 */
export type BaseDoc = {
    type: "profile" | "balance" | "trade" | "order" | "address" | "voucher" | "account" | "account" | "debit" | "credit" | "signature" | "request";
    pubkey: Base58PubKey;
    ulid: ULID;
}

/**
 * Signatures are cryptographic proofs verifiable by anyone.
 * 
 * - pubkey: creator and the signee
 * - hash: references a document being signed. The hash is calculated as bs58 encoded SHA-256 of a string
 * generated by json-stable-stringify of the document object. If the signature is not referencing a document 
 * using a hash property, then its sole purpose is to acknowledge the existence of other signatures.
 * - action: an optional field indicating the signee's statement
 *   - ack: indicates that the signee has seen the referenced document
 *   - ready: the signee (bank) confirms the validity and feasibility of the transaction record 
 * (e.g. the account exists and there are enough funds);
 *   - lead: the holder authorizes its bank to initiate hold and settlement ahead of other tx participants
 *   - follow: the holder authorizes its bank to hold only after other tx participants hold, and to settle only after they settle
 *   - held: the signee (bank) has successfully put a hold on the funds preparing to transfer them out from the account
 *   - settled: the signee (bank) has successfully updated the account balances
 *   - rejected: the signee refuses to process the document
 * - seen: optional references to other pre-existing signatures. This forms a directed acyclic graph of signatures 
 * and establishes a partial order.
 * - reason: optional human-readable reason for action, mostly relevant for rejections.
 * sig: basee58 encoded ed25519 signature of sha-256 hash produced from json-stable-stringify of this object without the sig property.
 */
export type Signature = BaseDoc & {
    hash?: Base58SHA256;
    action?: "ack" | "approve" | "hold" | "settle" | "reject" | "lead" | "follow";
    seen?: Base58Signature[]; // Previous signatures seen
    reason?: string;
    sig?: Base58Signature;
}

/*
* Vouchers describe a class of goods or services offered by the Pubkey Owner. Each voucher is bound to a particular Bank
* that is responsible for record keeping. As other documents, vouchers are immutable. To change a Bank, new Voucher
* needs to be created.
* 
* - pubkey: issuer of the voucher
* - bank: pubkey of the entity that maintains account balances and processes transactions, 
* - name: diplay name of the voucher
* - due: optional maturity date 
* - limit: the maximum number of vouchers that can be issued, not limit if not specified
* - integer: if holders can have only integer amounts of voucher; float by default
*/
export type Voucher = BaseDoc & {
    type: "voucher";
    bank: Base58PubKey;
    name: string;
    due?: DateString;
    limit?: number;
    integer?: boolean;
}

/**
 * Account is named set of accounts owned by a Holder. Typically holders will have multiple accounts serving different purposes.
 * 
 * - pubkey: account owner
 * - name: assigned by the owner; typically not visible to the public and even to the Bank because 
 * accounts are referenced by hash.
 */
export type Account = BaseDoc & {
    type: "account";
    name: string;
}

/**
 * Accounts are maintained by the Bank. Technically the Bank doesn't need account and voucher details to be able to 
 * process transactions. Knowing just the hashes of these objects is enough. Disclosure requirements are defined 
 * on a case-by-case basis by each Bank's policy.
 * 
 * - pubkey: account holder
 * - account: may or may not belong to the account holder; there could be standard "public" accounts; also the Bank may define 
 * public accounts for special purposes
 * - 
 */
export type Account = BaseDoc & {
    type: "account";
    account: Base58SHA256;
    voucher: Base58SHA256;
}

/**
 * An element of double-entry accounting system. Each Record has a correspondijng paired Record
 * 
 * - amount: the amount to transfer
 * - account: account from which funds are either debited or credited to
 * - pair: a Record that has the opposite type, same amount, same tx, and points back to this record using "pair" property
 * - tx: the transaction that this record is a part of
 * 
 * A record can never get processed separately from its pair. If there's a credit, there's a debit, and vice versa.
 * Records are processed by the bank through issuing signatures:
 * - "approve" for the credit record meaning the account exists and has the necessary amount; and the pair record is correct
 * - "approve" for the debit record meaning the pair record is correct
 * - "hold" for the credit record meaning the amount was put on hold and cannot be held by another credit record
 * - "settle" for credit and debit records meaning the account balances are updated accordingly
 * - "reject" for credit and debit records meaning the processing was abandoned; rejected records cannot be re-processed
 */
export type Record = BaseDoc & {
    type: "credit" | "debit";
    amount: number;
    account: Base58SHA256;
    pair: Base58SHA256;
    tx: Base58SHA256;
}

/** 
 * Tx (transaction) represents a single holder view of a barter deal: What I'm giving and what I'm getting in this exchange?
 * The whole barter deal may contain unlimited number of vouchers, holders, and banks. Each individual 
 * participant technically doesn't need to know the whole picture, but may require full disclosure in order to
 * agree to participate.
 * 
 * Tx can be authorized by the owner signature ("lead" or "follow" - see above for the explanation of the difference)
 * an order or an invoice. Txs are linked together using "pair" references from records. 
 * 
 * E.g. if A and B exchange vouchers X and Y, A will see a tx with debit X, credit Y records, 
 * while B will see a tx with debit Y, credit X records. Furthermore, A and B may not even know who are their counterparties
 * in this exchange. The X Bank will know that some amount of X exchanges hands between A and B, but won't know anything about 
 * the Y side of exchange (assuming Y is handled by another bank). Same for Y Bank.
 * 
 * A holder in a transaction can have a "lead" or a "follow" roles. The "lead" role assumes all the risks of
 * suspended or abandoned transactions because it is the first to hold and the first to settle. The "follow" role
 * only holds after everybody else confirmed a hold, and settle only after everybody else settled.
 * 
 * When processing tx records, banks determine the holder role based on how transaction is authorized:
 * - "lead" signature -> "lead" role
 * - "follow" signature -> "follow" role
 * - invoice -> "follow" role for the debit account owner
 * - order -> depending on the "lead" property of the Order
 * 
 * - pubkey: tx owner, which must be the owner of ALL accounts referenced by records.
 * - order, invoice, cheque: optional, can be only one of, 
 * - 
*/
export type Tx = BaseDoc & {
    type: "tx";
    order?: Base58SHA256;
    records: Base58SHA256[];
}

/**
 * Order represents a standing instruction for the Bank to process certain transactions. 
 * Orders have no expiration and are valid for as long as there is enough remaining balance in the credit account.
 * To deactive an order the issuer should empty the credit account.
 * 
 * - pubkey: should be the same as the owner of the credit and debit accounts
 * - rate: = debit_amount / credit_amount
 * - credit: credit account
 * - min: minimum amount to credit, prevents fragmentation
 * - debit: debit account
 * - limit: maximum amount in the debit account - prevents overstocking
 * - lead: if the order can be executed without confirmation from the credit account holder
 * - approvers: a list of pubkeys that may sign the tx as "lead" or "follow" and their signature would be treated 
 * as the owner's signature. If not specified, the owner's signature is required.
*/
export type Order = BaseDoc & {
    type: "order";
    rate: number;
    credit: Base58SHA256;
    min: number;
    debit: Base58SHA256;
    limit: number; 
    lead: boolean;
    approvers?: Base58PubKey[];
}

/**
 * User profile is a private data structure not intended for publishing.
 * It is used to store user's login, password hash, encrypted private key and addresss.
 */
export type Profile = BaseDoc & {
    login: string;
    passwordHash: Base58SHA256;
    encryptedPrivateKey: string;
    address: Address[];
}

/**
 * Contact is a data structure designed to hold an annotation to a address, such as name, 
 * comment or a list of related docs. A user may publish their own contact with their suggested name
 * and a list of related docs, such as the most recent versions of the address doc itself and the ledger address doc.
 * 
 * The user may also maintain a list of contacts in their profile. They can give addresss 
 * special names, add comments, or include useful docs in the list of related docs for easier access.
 */
export type ContactStruct = {
    name: string;
    comment?: string;
    pubkey: Base58PubKey;
    related?: Doc[];
}

/**
 * Address document contains the endpoints used to communicate with the holder.
 * - url is the endpoint of the node that is hosting the holder, can be used for inbox and orders
 * - ledger is the pubkey of the address that acts as the ledger for currencies emitted by the address
 * ledger may be the same as the holder.
 * 
 * The signee may issue a signed address with a newer ulid to update the url/ledger.
 * 
 * Nodes maintain public directories of address docs, indexed by pubkey. The address doc for a pubkey
 * can be updated by any anonymnous user on the internet, provided they have a signed address doc with a newer ulid.
 * 
 * API to manage the address directory:
 * - GET /address/<pubkey> - get the address doc for the pubkey, or a 404 if none is found
 * - POST /adress - create or update the address doc for the pubkey
 * 
 * The clients show try to update the addresses whenever they have a chance to make sure the updates
 * are propagated as quickly as possible.
 */
export type Address = BaseDoc & {
    type: "address";
    url?: string;
}





/**
 * JSON RPC 2.0
 * 
 */






export type Doc = Tx | Profile | Order | Address | Token | Account | Record | Invoice | Cheque;

export type Query = {
    pk: string;
    sk?: string;
    from?: string;
    limit: number;
}

export type Result = {
    ok: boolean;
    error?: string;
    item: ListItem
}

/*
* All requests are signed. Requests with ulid same or prior to the one already used 
* will be rejected with 403 code. Requests with invalid signature will also be rejected
* with 403.
*/
export type Request = BaseDoc & {
    type: "request";
    docs?: { [key: Base58SHA256]: Doc },
    sigs?: Signature[],
    queries?: { [key: string]: Query }
}

/*
* The server is streaming back an SSE with ResponseItems. Each item
* identifies a doc, signature or a query.
*/
export type ResponseItem = {
    result: Result;
    doc?: Base58SHA256;
    sig?: Base58Signature;
    query?: string;
}

export type ListItem = {
    sk: string;
    doc: Doc;
    related?: Doc[];
}

// post /send/pubkey
export type InboxItemDoc = BaseDoc & {
    type: "inbox";
    status: "unseen" | "seen" | "accepted" | "rejected" | "deleted" | "failed";
    doc: Doc;
    related?: Doc[];
}





// export type TokenBalance = {
//     token: Base58SHA256;
//     holder: Base58PubKey;
//     current: number;
//     incoming: number;
//     outgoing: number;
//     minted: number;
// }

// export type AccountBalance = TokenBalance & {
//     account: Base58SHA256;
// }

// export type Block = Signature & {
//     ulid: ULID;
//     prev: Base58Signature; // Previous block in the chain
// }